# Generated by Django 6.0.4 on 2026-05-28 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recuerdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('fecha_recuerdo', models.DateField(verbose_name='¿Cuándo pasó?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_recuerdo'],
            },
        ),
        migrations.CreateModel(
            name='MultimediaRecuerdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='recuerdos/', verbose_name='Foto o Vídeo')),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Vídeo')], default='imagen', max_length=10, verbose_name='Tipo de archivo')),
                ('pie_de_foto', models.TextField(blank=True, null=True, verbose_name='Pie de foto / vídeo')),
                ('recuerdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedias', to='historia.recuerdo')),
            ],
        ),
    ]
