# Generated by Django 6.0.4 on 2026-05-29 17:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimediarecuerdo',
            name='archivo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='archivo'),
        ),
    ]
